In [1]:
import numpy as np 

In [2]:
lst = [x**2 for x in range(0,10)]

a = np.array(lst)

In [6]:
print(a.size)
print(a.shape)
print(a.dtype)
print(a.ndim)

10
(10,)
int32
1


In [10]:
# practice on reshaping and flattering the array 

lst1 = np.arange(0,10).reshape(2,5)
print(lst1)
print(lst1.ravel())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [11]:
#now it's time to learn indexing in numpy array ; 

a  = np.arange(0,15,1).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
print(a[2][3])

13


In [14]:
print(a[1:,1:3])

[[ 6  7]
 [11 12]]


In [30]:
print(a[a>5].shape)  # it's for forgot the shape like flattering without knowing it 

(9,)


In [35]:
print(a[[1,2],[3,4]]) # it's give result in the way it's seems to follow this structure like reurns the a[1,3] elements and a[2,4] elements 

[ 8 14]


In [36]:
np.ones((3,5,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# inbuild function like univesral function  : 

print(a.mean())
print(a.std())
print(a.var())


7.0
4.320493798938574
18.666666666666668


In [47]:
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax())

0
14
0
14


In [51]:
# usefull array funciton 

a = np.arange(1,11,1).reshape(2,5)
b = np.linspace(1,2,6)
print(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1.  1.2 1.4 1.6 1.8 2. ]


In [58]:
# how good with random numbers 

a = np.random.rand(3,3)
print(a)
b = np.random.randint(1,100,(3,3))
print(b)
c = np.random.randn(3,5) # follows the gaussian distribution 
print(c)

[[0.19993119 0.40131844 0.65883644]
 [0.81926996 0.58552707 0.85712373]
 [0.13287328 0.23820948 0.7084105 ]]
[[23 10  7]
 [45 82 84]
 [98 38 98]]
[[-0.73719537 -1.19612589  0.66873709  0.16750324  1.21482044]
 [-2.50941624 -0.50062649 -0.90754843  0.06675496 -2.59947624]
 [-0.49265315  1.2571065   1.87207134 -0.76367451 -0.33005879]]


In [65]:
# matrix operation 

a = np.arange(1,16,1).reshape(3,5)
b =np.random.randint(1,30,(5,3))
c  = np.random.randint(1,100,(5,5))
print(np.dot(a,b))
print(a.T)
print(b.T)
print(np.linalg.det(c))
print(np.linalg.inv(c))

print(vel,vec)

[[ 251  287  124]
 [ 686  732  404]
 [1121 1177  684]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[18 28  7 14 20]
 [ 2 27 21 27 12]
 [19 10 24  2  1]]
-1258116885.999999
[[ 0.0078703  -0.01517975  0.01335424  0.00239406 -0.00064809]
 [-0.02252647  0.01144606  0.00530616 -0.00218697  0.00531911]
 [ 0.01136274 -0.00389017  0.01353262 -0.01058613 -0.0019244 ]
 [ 0.01757916 -0.00565727 -0.00697967  0.01336031 -0.01686373]
 [-0.00809698  0.01225875 -0.0160129   0.00134651  0.01429747]]
[212.70244394  78.79273714 -72.4555473  -35.41532752 -48.62430626] [[ 0.59232357  0.71411598  0.62395442 -0.5330953   0.63893538]
 [ 0.32580702 -0.1162003  -0.00133661  0.27481262 -0.29790054]
 [ 0.3830271  -0.33579541 -0.24656226 -0.3039503   0.00268724]
 [ 0.57617752  0.56923835 -0.70074613  0.73815643 -0.67493958]
 [ 0.25359866 -0.1993615   0.24257166  0.05501566  0.21786737]]


In [68]:
print(np.linalg.eig(c))
vel , vec = vel,vec = np.linalg.eig(c)
print(vel,vec)

EigResult(eigenvalues=array([263.47786226 +0.j        , -63.4105298  +0.j        ,
        49.2640388 +11.57583992j,  49.2640388 -11.57583992j,
        29.40458992 +0.j        ]), eigenvectors=array([[ 0.31482333+0.j        , -0.5790054 +0.j        ,
         0.07420568+0.03244868j,  0.07420568-0.03244868j,
        -0.33138049+0.j        ],
       [ 0.58176843+0.j        , -0.55084749+0.j        ,
        -0.39799613-0.24830156j, -0.39799613+0.24830156j,
         0.49680302+0.j        ],
       [ 0.48223901+0.j        ,  0.32890073+0.j        ,
        -0.46664976-0.26164227j, -0.46664976+0.26164227j,
         0.062178  +0.j        ],
       [ 0.52560994+0.j        ,  0.45069954+0.j        ,
         0.55049159+0.j        ,  0.55049159-0.j        ,
        -0.72129319+0.j        ],
       [ 0.23154156+0.j        ,  0.22363817+0.j        ,
         0.21218467+0.37296651j,  0.21218467-0.37296651j,
         0.3453169 +0.j        ]]))
[263.47786226 +0.j         -63.4105298  +0.j
  49.26403

In [76]:
# Questino 1 : numpy metrix operation : 
sales = np.array([
    [10, 15, 20],
    [5,  10, 15],
    [2,  8,  18]
])
for person in sales:
    print(person.sum())
for product in sales:
    print(product.max())
print(sales*1.1) # 10 % increse 



45
30
28
20
15
18
[[11.  16.5 22. ]
 [ 5.5 11.  16.5]
 [ 2.2  8.8 19.8]]


In [83]:
#question 2 : 
temps = np.array([32, 35, 28, 40, 38, 30, 31])
print(temps[temps > 30 ])
print(np.where(temps<30,30,temps))
print(np.sort(temps)[::-1])

[32 35 40 38 31]
[32 35 30 40 38 30 31]
[40 38 35 32 31 30 28]
